### ISSUE TITLE
Configurable runtime

### ISSUE THREAD

**Issue by epiphone** [serverless-components/backend#1]
Hi, so looking at [the code](https://github.com/serverless-components/backend/blob/master/serverless.js#L93) it seems like `runtime` is not configurable at the moment? If that's the case, is this by design, or...?

I'd be happy to submit a PR!

**Comment by eahefnawy** [comment]
Hey @epiphone ... yeah it only supports JS atm because the backend component adds [a JS shim](https://github.com/serverless-components/backend/blob/master/shim.js) during packaging. If we want to support other runtimes, we'll need to add this shim in other languages as well.

If your PR could also add this shim for whatever language you're targeting, we would merge that! 😊 

Thanks for pitching in!

**Comment by RodrigoEspinosa** [comment]
Hello! I understand that only node is available at the moment due to the shim. However, why sticking to a specific version where node10.x would be perfectly fine as well?

**Comment by eahefnawy** [comment]
@RodrigoEspinosa you're right! We should upgrade that to 10.x. PR is welcome!

**Comment by RodrigoEspinosa** [comment]
@eahefnawy, sounds good. Although, I'd make the runtime configurable so the user can pick between node8 or node10. If that's alright I'll create a PR.

**Comment by eahefnawy** [comment]
@RodrigoEspinosa sure thing. Just as long as 10.x is the default one and configuring it is completely optional.

**Comment by RodrigoEspinosa** [comment]
@epiphone, this is now available.
